# Generated by Django 4.1 on 2022-11-14 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newspage', '0002_alter_post_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategory',
            name='name_post_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newspage.category'),
        ),
    ]
