# Generated by Django 4.1 on 2022-11-19 15:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newspage', '0006_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='category',
            name='user_subscriber',
            field=models.ManyToManyField(through='newspage.Subscriber', to=settings.AUTH_USER_MODEL),
        ),
    ]
