# Generated by Django 4.1 on 2022-11-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_category',
            field=models.ManyToManyField(null=True, through='newspage.Postcategory', to='newspage.category'),
        ),
    ]
