# Generated by Django 4.1 on 2022-11-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspage', '0003_alter_postcategory_name_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name_category',
            field=models.CharField(default='В мире', max_length=255, unique=True),
        ),
    ]
