# Generated by Django 4.1 on 2022-11-22 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newspage', '0007_remove_category_subscribers_category_user_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategory',
            name='name_post_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newspage.category'),
        ),
    ]
