# Generated by Django 4.1 on 2022-12-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspage', '0008_alter_postcategory_name_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='information',
            field=models.TextField(default=1, verbose_name='Описание категории'),
            preserve_default=False,
        ),
    ]
